.TH curlbomb 1 2016\-04\-01
.SH SYNOPSIS
 \fBcurlbomb\fR [-h] [-k] [-n N] [-p PORT] [-c CMD] [-d host[:port]] [-w] [-l] [-q]
         [-v] [--ssh SSH_FORWARD] [--ssl CERTIFICATE] [--survey] [--unwrapped]
         [--disable-postback] [--client-logging] [--mime-type MIME_TYPE]
         [--version]
         [FILE]


.SH DESCRIPTION

.br

.br
curlbomb is an HTTP(s) server for serving one\-time\-use shell scripts.
.br

.br
You know all those docs for cool dev tools that start out by telling
.br
you to install their software in one line, like this?
.br

.br
    bash <(curl \-s http://example.com/install.sh)
.br

.br
I call that a curl bomb... I don't know if anyone else does.
.br

.br
curlbomb reads a file, or from stdin, and then serves it one time to
.br
the first client to retrieve it. A command is printed out that will
.br
construct the curl bomb the client needs to run, which includes a
.br
one\-time\-use passphrase (called a knock) required to download the
.br
resource. This command is copied and run in another shell, on some
.br
other computer, to download and run the script in one line.
.br

.br
curlbomb has optional integration with OpenSSH to make it easy to
.br
curlbomb from anywhere on the internet, to anywhere else, through a
.br
proxy server that you can forward the port through.
.br

.br

.SH EXAMPLES

.br

.br
Serve a script stored in a file:
.br

.br
    curlbomb /path/to/script
.br
	
.br
This outputs a curl command to run the script on another computer:
.br

.br
    KNOCK='nDnXXp8jkZKtbush' bash <(curl \-LSs http://192.0.2.100:48690)
.br

.br
By default, the client must pass a KNOCK variable that is passed in
.br
the HTTP headers. This is for two reasons:
.br

.br
 * It adds a factor of authentication. Requests without the knock are
.br
   denied.
.br
 * It helps to prevent mistakes, as the knock parameter is randomly
.br
   generated each time curlbomb is run and can only be used once. (\-n 1)
.br

.br
(Astute readers will notice that the KNOCK variable is being fed to
.br
the script that is being downloaded, not into the curl command. That's
.br
because it's really a curlbomb within a curlbomb. The first curl
.br
command downloads a script that includes a second curl command that
.br
*does* require the KNOCK parameter. This nesting allows us to keep the
.br
client command as short as possible and hide some extra
.br
boilerplate. See \-\-unwrapped.)
.br

.br
If you want the curl, without the bomb, ie. you just want to grab the
.br
script without redirecting it to bash, use \-\-survey. This is useful
.br
for testing the retrieval of scripts without running them.
.br

.br
You can also pipe scripts directly into curlbomb:
.br

.br
    echo "pacman \-\-noconfirm \-S openssh && systemctl start sshd" | curlbomb
.br
	
.br
Or from shell scripts:
.br

.br
    cat <<EOF | curlbomb
.br
    #!/bin/bash
.br
    echo "I'm a script output from another script on another computer"
.br
	EOF
.br

.br
Or type it interactively:
.br

.br
    $ curlbomb \-
.br
	pkg instll sqlite3
.br
	echo "bad idea, I don't have spollcheck when I typ in the terminal"
.br

.br
The shebang line (#!) is interpreted and automatically changes the
.br
interpreter the client runs:
.br

.br
    cat <<EOF | curlbomb
.br
	#!/usr/bin/env python3
.br
	import this
.br
	print("Hello, from Python!")
.br
	EOF
.br

.br
Note that the resource curlbomb sends doesn't need to be a
.br
script. Here's a useful command to send a tarball of your private SSH
.br
keys to another client you're setting up:
.br

.br
    tar cjh \-C $HOME .ssh | curlbomb \-c "tar xjv \-f"
.br

.br
The \-c parameter tells the client what command to run the resource with. By specifying "tar xj \-f" you are telling it to read the resource directly as a tarball and extract it.
.br

.br
By default, curlbomb constructs URLs with the IP address of the local
.br
machine. This usually means that clients on another network will be
.br
unable to retrieve anything from curlbomb, unless you have a port
.br
opened up through your firewall. As an alternative, curlbomb can be
.br
tunneled through SSH to another host that has the proper port
.br
open. For instance:
.br

.br
    echo "apt\-get install salt\-minion" | curlbomb \-\-ssh user@example.com:8080
.br
	
.br
The above command connects to example.com over SSH (port 22 by
.br
default) and forwards the local curlbomb HTTP port to
.br
example.com:8080. The URL that curlbomb prints out uses the domain
.br
name of the ssh server instead of the local IP address. The SSH tunnel
.br
is left open for as long as curlbomb remains running. Any user on
.br
example.com will be able to fetch the resource from
.br
localhost:8080. However, by default, SSH does not open this up to the
.br
rest of the world. If you want any client to be able to connect to
.br
example.com:8080 you will need to modify the sshd_config of the server
.br
to allow GatewayPorts:
.br

.br
	# Put this in your /etc/ssh/sshd_config and restart your ssh service:
.br
    GatewayPorts clientspecified
.br

.br
For extra security, you can enable TLS with \-\-ssl:
.br

.br
    echo "PASSWORD=hunter2 run_my_server" | curlbomb \-\-ssl /path/to/cert.pem
.br

.br
The example above is passing a bit of secure information; a
.br
password. Even without TLS, curlbomb secures access with a knock
.br
parameter. For many use\-cases, this is sufficient to secure it, as
.br
curlbombs are short lived and can only be retrieved one time (\-n
.br
1). However, the connection itself might be spied on through traffic
.br
analysis at your ISP or any other router your connection flows
.br
through. Using TLS makes sure this doesn't happen. 
.br

.br
Note that when combined with the \-\-ssh parameter, the SSL certificate
.br
should be generated for the host running the SSH server rather than
.br
the one running curlbomb. To prevent having to store the SSL
.br
certificate in plain text on your local machine, the file may be
.br
optionally PGP encrypted (ascii\-armored) and curlbomb will decrypt it
.br
only when necessary.
.br

.br
By now the curlbomb command might be getting quite long. Once you've
.br
encrypted and stored your SSL certificate, and setup your SSH server,
.br
create an alias for ease of use, for example:
.br

.br
    alias curlbomb_public=curlbomb \-\-ssl ~/.curlbomb/curlbomb.pem \-\-ssh user@example.com:22:8080
.br

.br
There's a few more examples in [EXAMPLES.md](EXAMPLES.md)
.br

.br

.SH OPTIONS

.br

.br
    usage: curlbomb.py [\-h] [\-k] [\-n N] [\-p PORT] [\-c CMD] [\-d DOMAIN] [\-w] [\-l]
.br
                       [\-q] [\-v] [\-\-ssh SSH_FORWARD] [\-\-ssl CERTIFICATE]
.br
                       [\-\-survey] [\-\-unwrapped] [\-\-disable\-postback]
.br
                       [\-\-client\-logging] [\-\-mime\-type MIME_TYPE] [\-\-version]
.br
                       [FILE]
.br
    
.br
\fB\fC\-k, \-\-disable\-knock\fR
Don't require a X\-knock HTTP header from the
.br
client. Normally curlbombs are one\-time\-use and meant to be
.br
copy\-pasted from terminal to terminal. If you're embedding into a
.br
script, you may not know the knock parameter ahead of time and so this
.br
disables that. This is inherently less secure than the default.
.br

.br
\fB\fC\-n N, \-\-num\-gets N\fR
The maximum number of times the script may be
.br
fetched by clients, defaulting to 1. Increasing this may be useful in
.br
certain circumstances, but please note that the same knock parameter
.br
is used for all requests so this is inherently less secure than the
.br
default. Setting this to 0 will allow the resource to be downloaded an
.br
unlimited number of times.
.br

.br
\fB\fC\-p PORT\fR
The local TCP port number to use.
.br

.br
\fB\fC\-c COMMAND\fR
Set the name of the command that the curlbomb is run with
.br
on the client. By default, this is autodected from the first line of
.br
the script, called the shebang (#!). If none can be detected, and one
.br
is not provided by this setting, the fallback of "bash" is used. Note
.br
that curlbomb will still wrap your script inside of bash, even with \-c
.br
specified, so the client command will still show it as running in
.br
bash. The command you specified is put into the wrapped script. See
.br
\-\-unwrapped to change this behaviour.
.br

.br
\fB\fC\-d host[:port], \-\-domain host[:port]\fR
Specify the domain name and
.br
port that is displayed in the URL of the client command. This does not
.br
change where the resource is actually located, use \-\-port or \-\-ssh for
.br
that. This is useful if you are setting up your own port forwards and
.br
need to show an external URL.
.br

.br
\fB\fC\-w, \-\-wget\fR
Print wget syntax rather than curl syntax. Useful in the
.br
case where the client doesn't have curl installed.
.br

.br
\fB\fC\-l, \-\-log\-posts\fR
Log the client output from the curlbomb server. 
.br

.br
\fB\fC\-q, \-\-quiet\fR
Be more quiet. Don't print the client curlbomb command.
.br

.br
\fB\fC\-v, \-\-verbose\fR
Be more verbose. Turns off \-\-quiet, enables
.br
\-\-log\-posts, and enables INFO level logging within curlbomb.
.br

.br
\fB\fC\-\-ssh SSH_FORWARD\fR
Forwards the curlbomb server to a remote port of
.br
another computer through SSH. This is useful to serve curlbombs to
.br
clients on another network without opening up any ports to the machine
.br
running curlbomb. The syntax for SSH_FORWARD is
.br
[user@]host[:ssh_port][:http_port]. The SSH server must have the
.br
GatewayPorts (see: man sshd_config) setting turned on to allow remote
.br
clients to connect to this port.
.br

.br
\fB\fC\-\-ssl CERTIFICATE\fR
Run the HTTP server with TLS encryption. Give the
.br
full path to your SSL certificate, optionally PGP (ascii\-armored)
.br
encrypted. The file should contain the entire certificate chain,
.br
including the CA certificate, if any.
.br

.br
\fB\fC\-\-survey\fR
Only print the curl (or wget) command. Don't redirect to a
.br
shell command. Useful for testing out script retrieval without running
.br
them.
.br

.br
\fB\fC\-\-unwrapped\fR
output the full curlbomb command, including all the
.br
boilerplate that curlbomb normally wraps inside of a nested curlbomb.
.br

.br
This parameter is useful when you want to source variables into your
.br
current shell:
.br

.br
    echo "export PATH=/asdf/bin:$PATH" | curlbomb \-c source \-\-unwrapped \-\-disable\-postback
.br

.br
Without the \-\-unwrapped option, the client command will not run the
.br
source command directly, but instead a bash script with a source
.br
inside it. This won't work for sourcing environment variables in your
.br
shell, so use \-\-unwrapped when you want to use
.br
source. \-\-disable\-postback prevents the command from being piped back
.br
to the server (as source doesn't have any output, and strangely fails
.br
to do it's job when you do pipe it somewhere else.)
.br

.br
\fB\fC\-\-disable\-postback\fR
Disables sending client output to the
.br
server. Note that \-\-log\-posts will have no effect with this enabled.
.br

.br
\fB\fC\-\-client\-logging\fR
Logs all client output locally on the client to a
.br
file called curlbomb.log
.br

.br
\fB\fC\-\-mime\-type MIME_TYPE\fR
The mime\-type header to send, by default
.br
"text/plain"
.br

.br
\fB\fC\-\-version\fR
Print the curlbomb version
.br

.br
\fB\fCFILE\fR
The script or other resource to serve via curlbomb. You can
.br
also leave this blank (or specify '\-') and the resource will be read
.br
from stdin.
.br

.SH AUTHORS
 Ryan McGuire <ryan@enigmacurry.com>
.SH DISTRIBUTION
 The latest version of curlbomb may be downloaded from https://github.com/EnigmaCurry/curlbomb